version: "3.8"
services:
  app:
    container_name: "grandmas_food_container"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/restaurant
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
    depends_on:
      - mysql
  mysql:
    container_name: "mysql"
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: restaurant
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
